[General]
discordUrl=https://lzc256.com
csfFile = general.csf

# Where game resources are located
gameresBaseUrl=/cdn/game-res/v2/
mapsBaseUrl=/cdn/maps/
modsBaseUrl=/cdn/mods/
gameResArchiveUrl=https://archive.org/download/red-alert-2-multiplayer/Red-Alert-2-Multiplayer.exe
patchNotesUrl=//www.ra2web.com/patch-notes.html
ladderRulesUrl=//www.ra2web.com/ladder-rules.html
modSdkUrl=https://github.com/ra2web/mod-sdk
breakingNewsUrl=/breaking-news.html
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
botsEnabled=yes
debugLogging=wol
defaultLanguage=zh-CN

viewport.width=1024
viewport.height=768
